version: '3.1'
  services:
  proxy:
    image: sawdog/traefik
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    deploy:
      mode: global
      placement:
        constraints:
          - "node.platform.os==linux"
          - "node.platform.architecture==i686"
          - "node.role==manager"
      restart_policy:
        condition: on-failure
    networks:
      - traefik_net
    labels:
     - traefik.enable=true
     - traefik.frontend.rule=Host:$TRAEFIK_FRONTEND_HOST
     - traefik.port=8080
     - traefik.docker.network=traefik_net
     - traefik.default.protocol=http
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /var/lib/docker/volumes:/var/lib/docker/volumes
     - /opt/traefik/traefik.toml:/traefik.toml
     - traefik-certs:/acme
 networks:
  traefik_net:
    external: true
    driver: overlay
    attachable: true
